// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aotlpaqsxqzpdkfghbkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvdGxwYXFzeHF6cGRrZmdoYmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODYxNzcsImV4cCI6MjA2MDU2MjE3N30.2A6MamKPm3LBx17pTuL_IrfJQFeR-ujVbJNOiUfV7Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);